version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=dino_wallet
    depends_on:
      - mysql_db
    networks:
      - dino-net

  mysql_db:
    image: mysql:8.0
    container_name: dino-wallet-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dino_wallet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Automatically runs seed.sql on first startup!
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - dino-net

networks:
  dino-net:
    driver: bridge

volumes:
  db_data: